from prompts._legacy_messages import (
    PORTFOLIO_RELEVANCE_ASSESSOR_SYSTEM_MESSAGE,
    PORTFOLIO_RELEVANCE_REVIEWER_SYSTEM_MESSAGE,
    PORTFOLIO_RELEVANCE_REVIEWER_USER_MESSAGE,
)

__all__ = [
    "PORTFOLIO_RELEVANCE_ASSESSOR_SYSTEM_MESSAGE",
    "PORTFOLIO_RELEVANCE_REVIEWER_SYSTEM_MESSAGE",
    "PORTFOLIO_RELEVANCE_REVIEWER_USER_MESSAGE",
]
