from prompts._legacy_messages import (
    SIGNPOST_EVALUATOR_SYSTEM_MESSAGE,
    SIGNPOST_EVALUATOR_USER_MESSAGE,
    SIGNPOST_GENERATOR_SYSTEM_MESSAGE,
    SIGNPOST_GENERATOR_USER_MESSAGE,
)

__all__ = [
    "SIGNPOST_GENERATOR_SYSTEM_MESSAGE",
    "SIGNPOST_GENERATOR_USER_MESSAGE",
    "SIGNPOST_EVALUATOR_SYSTEM_MESSAGE",
    "SIGNPOST_EVALUATOR_USER_MESSAGE",
]
